# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="PSCUST"
DIST_VERSION="0.09"


inherit perl-module

DESCRIPTION="Simple iterator with lookahead and unget"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND=">=perl-gcpan/Iterator-Simple-0.07
	>=dev-perl/Class-Accessor-0.510.0
	dev-lang/perl"
